#!/bin/bash

if [[ $# -eq 0 ]]; then
    echo "run node|mongo"
    exit 1
fi

prog=$1; shift
case $prog in
    n|node)
        prog=_node
        ;;
    m|mongo)
        prog=_mongo
        ;;
    *)
        echo "ERROR. Unknown program:" $prog
        exit 1
esac

# cd to project root
root_dir=$(dirname "${BASH_SOURCE}")
cd "$root_dir"

./bin/$prog "$@"

# todo install scripts
# if [[ $DEPS == true ]]; then
#     npm install --no-bin-links
# fi
